
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import {Canvas} from '@react-three/fiber'




export default function About() 

{



  // useEffect(() => {
  //   // Client-side-only code

  //   const geometry = new THREE.SphereGeometry();
 
  //   const material = new THREE.MeshBasicMaterial( { color: 0xffffff } );
    
  //   const sphere = new THREE.Mesh( geometry, material );
    
  //   const scene = new THREE.Scene();
  
    
  
  //   const renderer = new THREE.WebGLRenderer();
    
  //   const camera = new THREE.PerspectiveCamera( 75, window.innerWidth / window.innerHeight, 0.1, 1000 );

  //   //we are going to have the fov increment up and down based on scroll wheel event
    
  //   renderer.setSize( window.innerWidth, window.innerHeight );
    
  //   document.body.appendChild( renderer.domElement );
    
    
    
  //   scene.add( sphere );
    
  //   camera.position.z = 5;
    
  //   function animate() {
    
  //     requestAnimationFrame( animate );
    
  //     sphere.rotation.x += 0.01;
    
  //     sphere.rotation.y += 0.01;
      
  //   renderer.render( scene, camera );
    
  // }
    
    
  //  animate();

  //})



  return (
    
  
    <div className={styles.container}>

     
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>



        
  <Link href="/">
        <a>My first page</a>
      </Link>
       


        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
